version: "3.9"
services: 
  br_test_api:
    container_name: br_test_api
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    links:
      - br_test_db
    restart: always

  br_test_db:
    image: mysql
    container_name: br_test_db
    command: --default-authentication-plugin=caching_sha2_password
    # env_file: .env
      
    ports:  
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=br_test_password

    # volumes:
    #   - "./script:/docker-entrypoint-initdb.d"

