version: "3.8"
services: 
  br_test_api:
    container_name: br_test_api
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    links:
      - br_test_db
    restart: always
    depends_on: 
      - br_test_db

  br_test_db:
    image: mysql
    restart: always
    container_name: br_test_db
    command: --default-authentication-plugin=caching_sha2_password
    ports:  
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=br_test_password
    volumes:
      - ./script/francisco_valdez_prueba.sql:/docker-entrypoint-initdb.d/francisco_valdez_prueba.sql

